_BASE_: "s0_bv2_bifpn.yaml"
MODEL:
  FPN:
    OUT_CHANNELS: 64
  ROI_BOX_HEAD:
    CONV_DIM: 64
  ROI_SHARED_BLOCK:
    ASPP_DIM: 64
    CONV_HEAD_DIM: 64
SOLVER:
  MAX_ITER: 10
  STEPS: (330000, 370000)
TEST:
  EVAL_PERIOD: 390000