_BASE_: "Base-DensePose-Parsing-RCNN-FPN.yaml"
INPUT:
  FORMAT: "RGB"
MODEL:
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  BACKBONE:
    NAME: "build_efficientnetv2_bifpn_backbone"
  EFFICIENTNETS:
    NAME: "spnasnet_100"
    SCRIPTABLE: True
    PRETRAINED: True
    OUT_FEATURES: (1,2,3,4)
    NORM: "FrozenBN"
  FPN:
    IN_FEATURES: ["s1","s2","s3","s5"]
  ROI_BOX_HEAD:
    NUM_FC: 0
    NUM_CONV: 2
    POOLER_SAMPLING_RATIO: 0
    POOLER_TYPE: "ROIAlignV2"
  ROI_SHARED_BLOCK:
    NONLOCAL_ON: False
    CONV_HEAD_DIM: 256
  ROI_SHARED_HEAD:
    POOLER_SAMPLING_RATIO: 0
    POOLER_TYPE: "ROIAlignV2"
SOLVER:
  MAX_ITER: 130000
  STEPS: (100000, 120000)
TEST:
  EVAL_PERIOD: 130001